#!/bin/bash

#leaks --atExit -- ./dependencies/CTest/bin/test_app --gtest_color=yes

set -e
clear; clear

rm -rf build
mkdir build
cd build

cmake .. -DCMAKE_C_FLAGS="-g" -DCMAKE_CXX_FLAGS="-g"
cmake --build .

echo "===== MEMORY LEAK REPORT ====="
leaks --atExit -- ../dependencies/CTest/bin/test_app



# end page

