#!/bin/bash
clear;clear
cd dependencies/CTest/bin
echo "---------- enumerate tests ---------"
./test_app --gtest_list_tests
echo "------------------------------------"
lldb --batch -o "run --gtest_color=yes" -o "quit" ./test_app